### ISSUE TITLE
[REQUEST]: Multiple sources for multiple views

### ISSUE THREAD

**Issue by hhl88** [Priestch/document-viewer#2]
Hi there,
Firstly, many thanks for your helpful effort. I have tried and find it is quite easy to use. 

But when i test with multiple documents [https://github.com/Priestch/document-viewer/blob/main/demos/src/views/MultipleFiles.vue](https://github.com/Priestch/document-viewer/blob/main/demos/src/views/MultipleFiles.vue) and tried to modify source for each view. Meaning to say, each view has different source file. Unfortunately both views render same content.

Hopefully that you will support in the future. I appreciate your work

**Comment by Priestch** [comment]
@hhl88 I just use same source for quick demo purpose, the two viewer use same options currently, I will update to let them use it's own option and show different file.

**Comment by hhl88** [comment]
then I will wait for new version supporting multiple sources, because version 0.9.3 shows still only one source due to same options. Thanks for your quick support.

**Comment by Priestch** [comment]
@hhl88 Fixed in 0.9.7

**Comment by hhl88** [comment]
@Priestch Thanks a lot, work as expected :D. Hope that the project will be grown bigger.

**Comment by Priestch** [comment]
I'm glad it helps you!
