### ISSUE TITLE
[BUG]: new version 0.9.5 not working

### ISSUE THREAD

**Issue by hhl88** [Priestch/document-viewer#3]
Hi there, i have try a new version but it does not work any more

Steps:

1. npm create @document-kits/viewer@latest test
2. vite-vue-template
3. cd test
4. npm install
5. npm run dev
6. Open browser and navigate to http://localhost:5173/

<img width="1442" alt="Screenshot 2024-03-24 at 18 00 38" src="https://github.com/Priestch/document-viewer/assets/22619029/8350fc8b-83ca-4c05-80d5-bae700c05907">
<img width="878" alt="Screenshot 2024-03-24 at 18 04 05" src="https://github.com/Priestch/document-viewer/assets/22619029/bb336c3c-dde6-44e1-85e5-48333a6f041f">

**Comment by Priestch** [comment]
@hhl88 It's a known issue, I found a bug when tracing #2 , you can use 0.9.3 before I fix this issue.

**Comment by Priestch** [comment]
I rollback to the 0.9.3, it's back now.
