### ISSUE TITLE
[BUG]: Cannot start dev for new commit (version 0.9.5)

### ISSUE THREAD

**Issue by hhl88** [Priestch/document-viewer#4]
Hi there, 
i have pulled new commit and gave it a try, but got this error
<img width="1356" alt="Screenshot 2024-03-24 at 17 53 56" src="https://github.com/Priestch/document-viewer/assets/22619029/510923dc-ce61-4cf4-9b74-c1b8878b9f25">

**Comment by Priestch** [comment]
I will close this and tracing in #3
